#!/usr/bin/env bash
# find-team-id.sh — locate your Apple Development team id and write it into Local.xcconfig.
# Run this AFTER adding your Apple ID in Xcode → Settings → Accounts.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"

echo "==> Looking for a code-signing identity…"
# NOTE: no -v. A certificate created moments ago (or one whose chain the trust cache hasn't
# refreshed) can be absent from the "valid identities" list while being perfectly usable —
# that exact false negative sent a real user in circles. Verify explicitly below instead.
ids="$(security find-identity -p codesigning 2>/dev/null || true)"
if ! grep -q "Apple Development\|Mac Developer" <<<"$ids"; then
  cat <<'MSG'
No Apple Development identity found.

Add your Apple ID first — free, no paid membership needed:
  1. Xcode → Settings (⌘,) → Accounts
  2. "+" → Apple ID → sign in
  3. Select your Apple ID; you'll see a team named "<Your Name> (Personal Team)"
  4. Re-run this script.

Alternative with no Apple ID at all: create a self-signed code-signing certificate in
Keychain Access (Certificate Assistant → Create a Certificate → type "Code Signing"), then set
CODE_SIGN_IDENTITY to its name in Local.xcconfig. Any STABLE identity keeps TCC grants alive.
MSG
  exit 1
fi
echo "$ids" | sed 's/^/    /'

# The TEAM ID is the certificate subject's **OU** field — NOT the parenthetical in the common
# name (that is the certificate id, and the two genuinely differ). Getting this wrong produces a
# build that fails to sign with a confusing error.
pem="$(mktemp)"; trap 'rm -f "$pem"' EXIT
security find-certificate -c "Apple Development" -p > "$pem" 2>/dev/null || true
team="$(openssl x509 -in "$pem" -noout -subject 2>/dev/null | grep -oE 'OU=[A-Z0-9]{10}' | cut -d= -f2 | head -1)"

if [[ -n "$team" ]]; then
  if security verify-cert -c "$pem" -p codeSign >/dev/null 2>&1; then
    echo "==> certificate verifies for code signing"
  else
    echo "==> WARNING: certificate did not verify for code signing; signing may fail" >&2
  fi
fi
if [[ -z "$team" ]]; then
  echo "Found an identity but couldn't parse a 10-character team id from it." >&2
  echo "Open Xcode → Settings → Accounts → your team row, and set DEVELOPMENT_TEAM manually." >&2
  exit 1
fi

echo "==> Team id: $team"
cat > "$root/Local.xcconfig" <<CONF
// Machine-local signing settings — gitignored. Generated by scripts/find-team-id.sh.
// A STABLE identity is what keeps Accessibility/Automation grants alive across rebuilds (G7).
DEVELOPMENT_TEAM = $team
CONF
echo "==> Wrote $root/Local.xcconfig"
echo
echo "Next:  make dmg"
